### ISSUE TITLE
Can't deploy due to "Stack with id {stack_id} does not exist"

### ISSUE THREAD

**Issue by vboufleur** [globaldatanet/aws-firewall-factory#50]
Hi!

I'm trying aws-firewall-factory out for automating the deployment of WAF rules accross multiple account in my org. The problem is that I got stuck on the following error:

```
# vboufleur @ wiipo161 in ~/Development/vboufleur/aws-firewall-factory on git:master x [19:00:52] 
$ REGION=us-east-1 task deploy config=owasptopten

🏷  Version:   3.1.1 
👤 AWS Account used:   
                      115131055398 
🌎 CDK deployment region:  
                      us-east-1  


/home/vboufleur/Development/vboufleur/aws-firewall-factory/node_modules/@aws-sdk/smithy-client/dist-cjs/default-error-handler.js:8
    const response = new exceptionCtor({
                     ^
ValidationError: Stack with id WIIPO-WAF-OWASPTOPTEN-DEV-C02E5EAD7FCC5F66B9B7B06E6A1B856D does not exist
    at throwDefaultError (/home/vboufleur/Development/vboufleur/aws-firewall-factory/node_modules/@aws-sdk/smithy-client/dist-cjs/default-error-handler.js:8:22)
    at /home/vboufleur/Development/vboufleur/aws-firewall-factory/node_modules/@aws-sdk/smithy-client/dist-cjs/default-error-handler.js:18:39
    at de_DescribeStacksCommandError (/home/vboufleur/Development/vboufleur/aws-firewall-factory/node_modules/@aws-sdk/client-cloudformation/dist-cjs/protocols/Aws_query.js:1575:12)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at /home/vboufleur/Development/vboufleur/aws-firewall-factory/node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24
    at /home/vboufleur/Development/vboufleur/aws-firewall-factory/node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js:14:20
    at /home/vboufleur/Development/vboufleur/aws-firewall-factory/node_modules/@aws-sdk/middleware-retry/dist-cjs/retryMiddleware.js:27:46
    at /home/vboufleur/Development/vboufleur/aws-firewall-factory/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:7:26
    at Object.setOutputsFromStack (/home/vboufleur/Development/vboufleur/aws-firewall-factory/lib/tools/helpers.ts:183:25)
    at /home/vboufleur/Development/vboufleur/aws-firewall-factory/bin/aws-firewall-factory.ts:114:11
```

I tried searching in the files for the root cause of the error but I was not able to. What could cause this error?

**Comment by vboufleur** [comment]
This is the JSON that I put on `values/owasptopten.json` for testing the repo:

```
{
    "General": {
      "Prefix": "wiipo",
      "Stage": "dev",
      "S3LoggingBucketName": "wiipo-firewall-factory-logs",
      "CreateDashboard": true,
      "DeployHash": "c02e5ead7fcc5f66b9b7b06e6a1b856d",
      "FireHoseKeyArn": "",
      "SecuredDomain": [
        ""
      ]
    },
    "WebAcl": {
      "Name": "owasptopten",
      "Scope": "REGIONAL",
      "Type": "AWS::ApiGatewayV2::Api",
      "IncludeMap": {
        "account": [
          "115131055398"
        ]
      },
      "PreProcess": {
        "ManagedRuleGroups": [
          {
            "Vendor": "AWS",
            "Name": "AWSManagedRulesAmazonIpReputationList",
            "Version": "",
            "Capacity": 25
          },
          {
            "Vendor": "AWS",
            "Name": "AWSManagedRulesAnonymousIpList",
            "Version": "",
            "Capacity": 50
          },
          {
            "Vendor": "AWS",
            "Name": "AWSManagedRulesBotControlRuleSet",
            "Version": "",
            "Capacity": 50
          },
          {
            "Vendor": "AWS",
            "Name": "AWSManagedRulesCommonRuleSet",
            "Version": "",
            "Capacity": 700
          },
          {
            "Vendor": "AWS",
            "Name": "AWSManagedRulesKnownBadInputsRuleSet",
            "Version": "",
            "Capacity": 200
          },
          {
            "Vendor": "AWS",
            "Name": "AWSManagedRulesSQLiRuleSet",
            "Version": "",
            "Capacity": 200
          }
        ]
      },
      "PostProcess": {}
    }
  }
```

I just noticed that I haven't created the bucket `wiipo-firewall-factory-logs` yet because the account has reached the buckets quantity limit. I've requested AWS to increase this limit for testing. This could be the root cause of the error?

**Comment by vboufleur** [comment]
I also haven't created a bucket while bootstraping CDK for the account. As soon as AWS raises my bucket limit I'll retry it and let ya'll know here.

**Comment by daknhh** [comment]
1. You need to bootstrap your AWS Account for CDK. 
2. You also need to have few prequisites please follow the description in the readme for that: https://github.com/globaldatanet/aws-firewall-factory#%EF%B8%8F-prerequisites
3. "S3LoggingBucketName" &   "FireHoseKeyArn" are required values. 
4. You can check your value file with executing: task validateconfig config=YourConfigFie

**Comment by vboufleur** [comment]
I've got the same error again, after bootstraping CDK in the account, creating the logging bucket and checking the config. Can you please help me to debug it?

I'm using CDK v2, as v1 will be deprecated soon. Could this be the cause of the error? Here's a message from AWS:
```
This is the AWS CDK v2 Developer Guide. The older CDK v1 entered maintenance on June 1, 2022 and will now receive only critical bug fixes and security patches. New features will be developed for CDK v2 exclusively. Support for CDK v1 will end entirely on June 1, 2023.
```

Checking the config:
```
# vboufleur @ wiipo161 in ~/Development/vboufleur/aws-firewall-factory on git:master x [12:19:46] C:130
$ REGION=us-east-1 task validateconfig config=owasptopten
Your config values/owasptopten.json is valid.
```

The config JSON:
```
{
    "General": {
      "Prefix": "wiipo",
      "Stage": "dev",
      "S3LoggingBucketName": "sre-firewall-factory-logs-dev",
      "CreateDashboard": true,
      "DeployHash": "c02e5ead7fcc5f66b9b7b06e6a1b856d",
      "FireHoseKeyArn": "arn:aws:kms:us-east-1:115131055398:key/6e343b5b-8f8a-454d-925d-ef166007b9a8",
      "SecuredDomain": [
        "dev.wiipo.com",
        "albsp.wiipo.com"
      ]
    },
    "WebAcl": {
      "Name": "owasptopten",
      "Scope": "REGIONAL",
      "Type": "AWS::ApiGatewayV2::Api",
      "IncludeMap": {
        "account": [
          "115131055398"
        ]
      },
      "PreProcess": {
        "ManagedRuleGroups": [
          {
            "Vendor": "AWS",
            "Name": "AWSManagedRulesAmazonIpReputationList",
            "Version": "",
            "Capacity": 25
          },
          {
            "Vendor": "AWS",
            "Name": "AWSManagedRulesAnonymousIpList",
            "Version": "",
            "Capacity": 50
          },
          {
            "Vendor": "AWS",
            "Name": "AWSManagedRulesBotControlRuleSet",
            "Version": "",
            "Capacity": 50
          },
          {
            "Vendor": "AWS",
            "Name": "AWSManagedRulesCommonRuleSet",
            "Version": "",
            "Capacity": 700
          },
          {
            "Vendor": "AWS",
            "Name": "AWSManagedRulesKnownBadInputsRuleSet",
            "Version": "",
            "Capacity": 200
          },
          {
            "Vendor": "AWS",
            "Name": "AWSManagedRulesSQLiRuleSet",
            "Version": "",
            "Capacity": 200
          }
        ]
      },
      "PostProcess": {}
    }
  }
  ```
  
  The error:
  ```
# vboufleur @ wiipo161 in ~/Development/vboufleur/aws-firewall-factory on git:master x [12:17:34] 
$ REGION=us-east-1 task deploy config=owasptopten

🏷  Version:   3.1.1 
👤 AWS Account used:   
                      115131055398 
🌎 CDK deployment region:  
                      us-east-1  


/home/vboufleur/Development/vboufleur/aws-firewall-factory/node_modules/@aws-sdk/smithy-client/dist-cjs/default-error-handler.js:8
    const response = new exceptionCtor({
                     ^
ValidationError: Stack with id WIIPO-WAF-OWASPTOPTEN-DEV-C02E5EAD7FCC5F66B9B7B06E6A1B856D does not exist
    at throwDefaultError (/home/vboufleur/Development/vboufleur/aws-firewall-factory/node_modules/@aws-sdk/smithy-client/dist-cjs/default-error-handler.js:8:22)
    at /home/vboufleur/Development/vboufleur/aws-firewall-factory/node_modules/@aws-sdk/smithy-client/dist-cjs/default-error-handler.js:18:39
    at de_DescribeStacksCommandError (/home/vboufleur/Development/vboufleur/aws-firewall-factory/node_modules/@aws-sdk/client-cloudformation/dist-cjs/protocols/Aws_query.js:1575:12)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at /home/vboufleur/Development/vboufleur/aws-firewall-factory/node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24
    at /home/vboufleur/Development/vboufleur/aws-firewall-factory/node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js:14:20
    at /home/vboufleur/Development/vboufleur/aws-firewall-factory/node_modules/@aws-sdk/middleware-retry/dist-cjs/retryMiddleware.js:27:46
    at /home/vboufleur/Development/vboufleur/aws-firewall-factory/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:7:26
    at Object.setOutputsFromStack (/home/vboufleur/Development/vboufleur/aws-firewall-factory/lib/tools/helpers.ts:183:25)
    at /home/vboufleur/Development/vboufleur/aws-firewall-factory/bin/aws-firewall-factory.ts:114:11

Subprocess exited with error 1
task: Failed to run task "deploy": task: Failed to run task "cdkdeploy": exit status 1
  ```

Here's the parameters of the CloudFormation stack for bootstraping CDK in the account:
![Screenshot_20230418_122623](https://user-images.githubusercontent.com/16310611/232826076-07ad22ea-4af3-4122-ba3c-ddfd1a0b21b1.png)

This is the template for bootstraping the CDK that I used: https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk/lib/api/bootstrap/bootstrap-template.yaml
